### ISSUE TITLE
Default setup: problems connecting to docker API

### ISSUE THREAD

**Issue by martinfiers** [ptone/jiffylab#19]
Hello,

When following the installation instructions from the linux-setup.sh file, I get the following error from the flask web-site when trying to log in:

https://gist.github.com/anonymous/dee890e89e7ecd984d26

After some searching, I found out how to solve it, although I don't exactly understand why this is needed. Solution:

In the _/etc/init/docker.conf_ file, there's this line:

```
exec /usr/local/bin/docker -d
```

Running docker as such gives the following:

```
test@test:~$ docker -H 127.0.0.1:4243 ps
2013/08/15 11:22:38 dial tcp 127.0.0.1:4243: connection refused
test@test:~$ sudo docker  ps
ID                  IMAGE               COMMAND             CREATED             STATUS              PORTS
```

This is exactly what the app.py tries (through the python docker API): to access docker on 127.0.0.1:4243 (just like on the command-line, docker -H 127.0.0.1:4243).

I solved the problem by modifying the exec line in _/etc/init/docker.conf_ 

```
exec /usr/local/bin/docker -H 0.0.0.0:4243 -d
```

Probably, there's a better solution, because when you install docker on a default ubuntu setup (13.04), you don't want to modify the docker.conf file to reduce setup time. I tried to start up the docker client:

```
docker_client = client.Client(url),
```

where for url I tried '0.0.0.0:4243', 'my.ip.add.ress:4243', and '127.0.0.1:4243', but none of them works.

With kind regards

**Comment by ptone** [comment]
Thanks for this report

Since this was first released, Docker moved to a file based socket connection, instead of the port based HTTP

I've just pushed some changes that now use the socket file - the key is to add the non-root user to the 'docker' group

I've just tested this latest push with both DigitalOcean and Rackspace - I find virtualbox a bit too sluggish on my development machine, and the cloud providers have such blazing download speeds.  The whole setup process only takes a couple minutes on DigitalOcean...

**Comment by martinfiers** [comment]
Thanks for the modification. I don't need to modify the docker setup anymore now.

However, as far as I know there is no docker group. See also: https://github.com/dotcloud/docker/issues/1471

So I have to start the web app as sudo, but that's an external issue now.

**Comment by ptone** [comment]
see:

https://github.com/ptone/jiffylab/blob/master/linux-setup.sh#L35
